### PR TITLE
Map scroll bar

### PR DESCRIPTION
**Pull request by jogibear9988**
A Map ScrollBar in AvalonEdit like in VisualStudio!
(uses a second Texteditor instance, wich will be fully rendered, so Performance is maybe not good at large files! And also SyntaxHighlightning on the Second Editor needs tobe impl.)
(also collaps/expand as in VS is not there,but it's a start)

image

Sorry for the Pull req beeing so big, but when my previous WPF Designer Patch is merged, only one commit is left!)

### CODE REVIEW

**Comment by jogibear9988** [comment]
I'm working on this at the Moment!

Has anyone a Idea,I need the Stretch in the VisualBrush to work like StretchVerticalyUniformToFill

**Comment by jogibear9988** [comment]
Now it looks like this in SD:

image

Problem is, it does not used the Highlighters wich the normal Text Editor uses. I tried to also add the Highlighters to the second TextView, but they can only be attached to one TextView!

I've no good Idea how to solve this atm.!

**Comment by jogibear9988** [comment]
Todo for this:

- Highlightning in the TextArea for the Map ScrollBar
- Setting in SD to Enable/Disable (The Editor already has one (default disabled))
- Maybe a option to disable automaticaly on large Files (because of Performance))
 (Need to investigate on wich File Size we got Performance issues!)

**Comment by dgrunwald** [comment]
I don't think this feature should be added to AvalonEdit itself, I'd like to keep the library a small, extensible text editor. The code for this should probably live in AvalonEdit.AddIn (like the existing EnhancedScrollBar that shows compiler errors).

On performance: AvalonEdit generally works well with large files (but not with long lines) -- I think my testcase for big files was 1 million lines with 80 characters per line.
Worst-case editing operation: hold Enter pressed to insert a bunch of new empty lines. You'd have to re-render the whole document on every keypress. Given the abysmal WPF text rendering performance, I'd expect you can't keep up with the keyboard repeat rate at less than 300 lines.
And beware of old hardware: an old laptop with intel integrated graphics couldn't even keep up with normal typing speed before the DrawingVisual optimization. You run a real risk of ruining the performance for a lot of people here.

Also, when you implement syntax highlighting, note that this ruins the incremental approach to syntax highlighting updates. In particular, typing `/*` would cause the highlighter to re-highlight the whole document (or up to the next `*/` if there is one), where currently the highlighter stops at the bottom of the visible area.

**Comment by jogibear9988** [comment]
quote: "You run a real risk of ruining the performance for a lot of people here." -> because of this, I would disable it when the Files is to big. Also we could disable it as default!

I will still work on this a bit, than you can decide to merge or drop it! 

What I still need, is a Idea how to clone the Highlightning so it also works in the second instance! Have you any Idea for this?

**Comment by dgrunwald** [comment]
For the highlighting, you could create another `HighlightingColorizer` for the second instance based on the same `IHighlighter`. 
At least the normal `DocumentHighlighter` should support being used from multiple text views at the same time. This way, the cached highlighting state is shared between the main view and the scroll bar.
I'm not sure if the C# semantic highlighter used in SharpDevelop supports being used in multiple text views, though. (but fixing it to allow use in multiple text views would be preferrable over cloning it, so that semantic analysis doesn't need to run twice)

I think you should test the performance first before investing more work in this; I fear that the limit for 'file too big' is so low that it makes the feature pretty much useless. You might have to look for alternative approaches that perform better (don't update on every keypress; maybe render on background thread; just draw lines instead of text when the font size gets too small; ...).

**Comment by jogibear9988** [comment]
It's not performant enough -> close

**Pull request closed without merging**
