### PR TITLE
Few fixes & addons for WPF Designer

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by Rpinski** [comment]
Hi Jochen,

With your PR 3 unit tests from *WpfDesign.Tests.Designer.ModelTests* start to fail. Can you have a look at them?

**Comment by jogibear9988** [comment]
Sorry! Will fix them ASAP! (In the next few hours)

**Comment by jogibear9988** [comment]
Now the Tests work again!

**Comment by jogibear9988** [comment]
Could we not use AppVeyor (or smth. similar), wich also builds the Pull Req's, and Tests them?

**Comment by Rpinski** [comment]
Thanks!

**Pull request merged**
