### PR TITLE
Assembly Info Editor. TextBox for assembly informational version.

### PR DESCRIPTION
**Pull request by olegbevz**
We can put any string for assembly informational version, not just "1.0.0.0" string.
Link: http://stackoverflow.com/questions/64602/what-are-differences-between-assemblyversion-assemblyfileversion-and-assemblyin.
So there should be a textbox for assembly informational version on assembly info panel .

### CODE REVIEW

**Comment by siegfriedpammer** [comment]
Thanks for your pull request. Please mind tabs vs. spaces in the indentation. Can you fix your commit and do a force push or create a new pull request?

**Comment by olegbevz** [comment]
I've fixed the indenting at AssemblyInfoProvider.cs 133.
Is it all right now?

**Comment by Rpinski** [comment]
Yep, looks ok now. Thank you!

**Comment by Rpinski** [comment]
@olegbevz Please pay attention to the unit tests in future pull requests, because code changes might break the unit test project or at least cause some tests to fail.

**Comment by olegbevz** [comment]
Sorry, too many mistakes from me: indenting and broken tests. Maybe it's because i had holidays. I'll be more attentive in future.

**Pull request merged**
