### PR TITLE
Returning compiler generaded methods back

### PR DESCRIPTION
**Pull request by ddur**
This code is distributed under MIT license (do not remember exact words)

### CODE REVIEW

**Comment by ddur** [comment]
Do not know why some old, already committed changes are here again.

**Comment by mrward** [comment]
So there is just the [one commit](https://github.com/ddur/SharpDevelop/commit/97d65bd39970ac7385e9a80f3c69d964a389c79c) you are interested in being added?

**Comment by ddur** [comment]
@mrward, yes, that one. Rest is already there, as far as I have checked some recent time ago.

**Comment by mrward** [comment]
I have cherry picked the commit across to the master branch. Thanks.

**Comment by ddur** [comment]
Thank You!

**Pull request closed without merging**
